version: "3.8"

services:
  # Backend Symfony (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - symfony_cache:/app/var/cache
      - symfony_log:/app/var/log
    expose:
      - "9000"
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://root@mysql/gordopower
    depends_on:
      - mysql

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # Base de Datos MySQL
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gordopower
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/gordopower.sql:/docker-entrypoint-initdb.d/gordopower.sql
    ports:
      - "3306:3306"

  # phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  # Servidor Web (Nginx)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  symfony_cache:
  symfony_log:
